// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Controllers.Models;

#nullable disable

namespace WebApp.Migrations
{
    [DbContext(typeof(MyDBContext))]
    partial class MyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApp.Controllers.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });
            modelBuilder.Entity("WebApp.Controllers.Models.Cliente", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("NombreDeUsuario")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("CorreoElectronico")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ContactoPrincipal")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Moneda")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Telefono")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Celular")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("SitioWeb")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("InfoAdicional")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Asesor")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ZonaSector")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Cliente");
            });
            modelBuilder.Entity("WebApp.Controllers.Models.Contacto", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Cliente")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Tipo")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Motivo")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Telefono")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("CorreoElectronico")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Estado")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Direccion")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ZonaSector")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Asesor")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Descripcion")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("idModulo")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");


                b.HasKey("Id");

                b.ToTable("Contacto");
            });
            modelBuilder.Entity("WebApp.Controllers.Models.Producto", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("Codigo")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Activo")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Descripcion")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Familia")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PrecioEstandar")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Producto");
            });
            modelBuilder.Entity("WebApp.Controllers.Models.Cotizacion", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("Numero")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("NombreOportunidad")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Fecha")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("NombreCuenta")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("MesAnnoProyectado")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Asesor")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("FechaCierre")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Etapa")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Moneda")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Probabilidad")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("OrdenCompra")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Tipo")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Descripcion")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ZonaSector")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Contacto")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("NumeroFactrura")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Estado")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Inflacion")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");


                b.HasKey("Id");

                b.ToTable("Cotizacion");
            });

#pragma warning restore 612, 618
        }
    }
}
